language: python

python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

env:
  - DJANGO=2.1.2

addons:
  postgresql: "9.4"

services:
  - postgresql

before_install:
  - pip install -U pip
  - export DJANGO_SETTINGS_MODULE=bzw_ops.settings
  - export PYTHONPATH=$PYTHONPATH:$HOME/builds/adrianboyko/xerocraft-django
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - python manage.py test
